apiVersion: v1
kind: Service
metadata:
  name: k8sready-springboot
spec:
  type: ClusterIP
  selector:
    app: k8sready-springboot
  ports:
    - name: "http"
      protocol: TCP
      # Don't forget to change the server port in the application.properties and in the Dockerfile too
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8sready-springboot
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: k8sready-springboot
                port:
                  # Don't forget to change the server port in the application.properties and in the Dockerfile too
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sready-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sready-springboot
  template:
    metadata:
      labels:
        app: k8sready-springboot
    spec:
      containers:
        - name: k8sready-springboot
          # Don't forget to change the version number in the build.gradle and in the Dockerfile too
          image: k8sready-springboot:0.0.1
          ports:
            - containerPort: 80
